name: Events Demo 1
on: 
  pull_request:
    types: 
      - opened
    branches:
      - main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
    paths-ignore:
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: |
          echo "Event data: ${{ toJson(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install depencencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project..."
      